/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package widok;

import Algorytmy.FastConvexHull;
import Algorytmy.SlowConvexHull;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.LinkedList;
import klasy.Punkt;
import klasy.Zbior;

/**
 *
 * @author karol
 */
public class secondFrame extends javax.swing.JFrame {

    Zbior S;

    /**
     * Creates new form secondFrame
     */
    public secondFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jsFastIloscPunktow = new javax.swing.JSlider();
        jlIlePunktowWybrano = new javax.swing.JLabel();
        jbStartSlow = new javax.swing.JButton();
        jpSlow = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlSlowCzas = new javax.swing.JLabel();
        jlSlowObroty = new javax.swing.JLabel();
        jpFast = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlFastCzas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlFastObroty = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(251, 0), new java.awt.Dimension(251, 0), new java.awt.Dimension(251, 32767));
        jbStartFast = new javax.swing.JButton();
        jsSlowIloscPunktow = new javax.swing.JSlider();
        jlIlePunktowWybrano1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Proszę wybrać ilość punktów do sumulacji");

        jsFastIloscPunktow.setMajorTickSpacing(200);
        jsFastIloscPunktow.setMaximum(10000000);
        jsFastIloscPunktow.setMinimum(100);
        jsFastIloscPunktow.setMinorTickSpacing(200);
        jsFastIloscPunktow.setSnapToTicks(true);
        jsFastIloscPunktow.setExtent(100);
        jsFastIloscPunktow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsFastIloscPunktowStateChanged(evt);
            }
        });

        jlIlePunktowWybrano.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlIlePunktowWybrano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jsFastIloscPunktow, org.jdesktop.beansbinding.ELProperty.create("${value}"), jlIlePunktowWybrano, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jbStartSlow.setText("START");
        jbStartSlow.setEnabled(false);
        jbStartSlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartSlowActionPerformed(evt);
            }
        });

        jpSlow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SlowConvexHull", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Czas wykonania :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Liczba obrotów głównej pętli");

        jlSlowCzas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlSlowCzas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSlowCzas.setText("0");

        jlSlowObroty.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlSlowObroty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSlowObroty.setText("0");

        javax.swing.GroupLayout jpSlowLayout = new javax.swing.GroupLayout(jpSlow);
        jpSlow.setLayout(jpSlowLayout);
        jpSlowLayout.setHorizontalGroup(
            jpSlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSlowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSlowCzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpSlowLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jpSlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(jlSlowObroty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpSlowLayout.setVerticalGroup(
            jpSlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSlowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSlowCzas)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSlowObroty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFast.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FastConvexHull", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jpFast.setPreferredSize(new java.awt.Dimension(283, 239));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Czas wykonania :");

        jlFastCzas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlFastCzas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFastCzas.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Liczba obrotów głównej pętli");

        jlFastObroty.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlFastObroty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFastObroty.setText("0");

        javax.swing.GroupLayout jpFastLayout = new javax.swing.GroupLayout(jpFast);
        jpFast.setLayout(jpFastLayout);
        jpFastLayout.setHorizontalGroup(
            jpFastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFastLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jpFastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(jpFastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFastCzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlFastObroty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpFastLayout.setVerticalGroup(
            jpFastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFastLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlFastCzas)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlFastObroty)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jbStartFast.setText("START");
        jbStartFast.setEnabled(false);
        jbStartFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartFastActionPerformed(evt);
            }
        });

        jsSlowIloscPunktow.setMajorTickSpacing(1);
        jsSlowIloscPunktow.setMaximum(2000);
        jsSlowIloscPunktow.setMinimum(1);
        jsSlowIloscPunktow.setMinorTickSpacing(1);
        jsSlowIloscPunktow.setSnapToTicks(true);
        jsSlowIloscPunktow.setValue(10);
        jsSlowIloscPunktow.setExtent(1);
        jsSlowIloscPunktow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsSlowIloscPunktowStateChanged(evt);
            }
        });

        jlIlePunktowWybrano1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlIlePunktowWybrano1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jsSlowIloscPunktow, org.jdesktop.beansbinding.ELProperty.create("${value}"), jlIlePunktowWybrano1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Prezentacja algorytmu dla niewielkiej ilości punktów");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jbStartSlow, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbStartFast, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jsSlowIloscPunktow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlIlePunktowWybrano1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlIlePunktowWybrano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsFastIloscPunktow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpSlow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jpFast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsFastIloscPunktow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlIlePunktowWybrano, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsSlowIloscPunktow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlIlePunktowWybrano1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbStartSlow, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbStartFast, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFast, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jpSlow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsFastIloscPunktowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsFastIloscPunktowStateChanged

        WyczyscFast();
        jbStartFast.setEnabled(true);


    }//GEN-LAST:event_jsFastIloscPunktowStateChanged
    /**
     * Uruchamia działanie algorytmu SlowConvexHull oraz prezentuje wynii jego
     * działania w odpowiednich polach
     */
    private void jbStartSlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartSlowActionPerformed
        jsSlowIloscPunktow.setEnabled(false);

        S = new Zbior(jsSlowIloscPunktow.getValue());

        LinkedList<Punkt> _Lslow;
        SlowConvexHull slow;

        slow = new SlowConvexHull(jpSlow);
        _Lslow = slow.AlgorytmSCH_Big(S);
        jlSlowObroty.setText(Long.toString(slow.getObroty()));
        jlSlowCzas.setText(Long.toString(slow.getCzas()) + "ms");

        jsSlowIloscPunktow.setEnabled(true);
    }//GEN-LAST:event_jbStartSlowActionPerformed
    /**
     * Uruchamia działanie algorytmu ConvexHull oraz prezentuje wynii jego
     * działania w odpowiednich polach
     */
    private void jbStartFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartFastActionPerformed

        jsFastIloscPunktow.setEnabled(false);

        S = new Zbior(jsFastIloscPunktow.getValue());

        LinkedList<Punkt> _Lfast;
        FastConvexHull fast;

        fast = new FastConvexHull(jpFast);
        _Lfast = fast.AlgorytmWydajnyCH_Big(S);
        jlFastObroty.setText(Integer.toString(fast.getObroty()));
        jlFastCzas.setText(Long.toString(fast.getCzas()) + "ms");

        jsFastIloscPunktow.setEnabled(true);
    }//GEN-LAST:event_jbStartFastActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed
    /**
     * Usuwa obecne okno i tworzymy okno podstawowego trybu
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        mainFrame mf = new mainFrame();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        mf.setLocation(dim.width / 2 - mf.getSize().width / 2, dim.height / 2 - mf.getSize().height / 2);
        mf.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jsSlowIloscPunktowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsSlowIloscPunktowStateChanged
        WyczyscSlow();
        jbStartSlow.setEnabled(true);
    }//GEN-LAST:event_jsSlowIloscPunktowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secondFrame().setVisible(true);
            }
        });
    }

    /**
     * Przy zmianie watrości slidera czyści pola na których wyswietlane były
     * wyniki działania algorytmu.
     */
    public void WyczyscFast() {
        jlFastCzas.setText("0");
        jlFastObroty.setText("0");
    }

    /**
     * Przy zmianie watrości slidera czyści pola na których wyswietlane były
     * wyniki działania algorytmu.
     */
    public void WyczyscSlow() {
        jlSlowCzas.setText("0");
        jlSlowObroty.setText("0");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbStartFast;
    private javax.swing.JButton jbStartSlow;
    private javax.swing.JLabel jlFastCzas;
    private javax.swing.JLabel jlFastObroty;
    private javax.swing.JLabel jlIlePunktowWybrano;
    private javax.swing.JLabel jlIlePunktowWybrano1;
    private javax.swing.JLabel jlSlowCzas;
    private javax.swing.JLabel jlSlowObroty;
    private javax.swing.JPanel jpFast;
    private javax.swing.JPanel jpSlow;
    private javax.swing.JSlider jsFastIloscPunktow;
    private javax.swing.JSlider jsSlowIloscPunktow;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
